// START OF MUSICIAN NAME SETS

var JSONmusicianNamesRockstar = [
'Jason Donner-Kebab'
,'By George'
,'Tina Turnoff'
,'Iggy Carrust'
,'Dorrissey'
,'Bill Collins'
,'Scratch N Sniff'
,'Sidney Sparkle'
,'Wacky Jacko'
,'Elvin Dwight'
,'Bimbo Baggins'
,'Maradonna'
,'Lumme'
,'Mince'
,'Rick Ghastley'
,'Dick Knackered'
,'Gracey Chapperson'
,'Eddy Quicksilver'
,'John Michael'
,'Kate Bushed'
,'Snoozy Sue'
,'Peter Gobsmacked'
,'Frank Zipper'
,'Rotton Johnny'
,'Bonehead'
,'Rupert Beetle'
,'Meathead'
,'Annie Smallpox'
,'Bryan Nylon'
,'Sneezy Wonderful'
,'Dingo Strapp'
,'Sadd'
,'Freddy Grunt'
,'Derek Claptout'
,'Bruce Stringbean'
,'Stiff Pilchards'
,'Alison Nightmare'
,'Crispy Rind'
,'Michael Gorge'
,'Izzy Azbeen'
,'Witless Houston'
,'Titchy Blackhead'
,'String'
,'Harry Human'
,'Rodney Holder'
,'Ted Newsagent'
,'Midge Sewer'
];

var JSONmusicianNamesMorris = [
'Alabaster Codify'
,'Alison Shithe'
,'Austen Tasseltine'
,'Barbara Wintergreen'
,'Barnaby Primp'
,'Benpole Bambendy'
,'Bidley Bodley Wilson'
,'Brant'
,'Brian Veltcher'
,'Chesney Christ'
,'Chingford Frock-Battery'
,'Clint Hyperwatchtick'
,'Clint Rimmer'
,'Colin Poppshed'
,'Collaterlie Sisters'
,'Condublasney Piper'
,'David Bovvinge'
,'David Compression'
,'David Jatt'
,'David Qunt'
,'David Sanction'
,'Dick Hickory'
,'Donnnald Beth&#39;l&#39;hem'
,'Douglas Trochs'
,'Engelbert Impromptu'
,'Eugene Fraxby'
,'Fact Portugal'
,'Gary Riot'
,'Gintilly Roundabout'
,'Gloriora Paymaster'
,'Graham Shithe'
,'Gypsum Fantastic'
,'Hugh Maharggs'
,'Iggy Pop Barker'
,'Jaques Liverot'
,'Judy Lehewuttwohen'
,'Keith Boo-ha-ha'
,'La-di-da Hardcastle'
,'Lardon Irridesco'
,'Larkagin Babs'
,'Barry Harribean'
,'Massingbird Massingbird'
,'Melton Stitt'
,'Patrick College'
,'Patrick Da Fronk'
,'Pervis Grundy'
,'Peter O&#39;Hanraha-hanrahan'
,'Peter Phile'
,'Peter Sisters-Christmas'
,'Pheona Haahlam'
,'Phillip Phillip Annoyman'
,'Polly Pantomime'
,'Romo Metaxxas'
,'Rosie May'
,'Simeon Sameon'
,'Sophie Valve'
,'Stephen Hole-hoisery'
,'Sylvester Stuart'
,'Tascam Holiday'
,'Ted Maul'
,'Tommy Territory'
,'Valerie Sinatra'
];

var JSONmusicianNamesSimple = [
'Musician 1'
,'Musician 2'
,'Musician 3'
,'Musician 4'
,'Musician 5'
,'Musician 6'
,'Musician 7'
,'Musician 8'
,'Musician 9'
,'Musician 10'
,'Musician 11'
,'Musician 12'
,'Musician 13'
,'Musician 14'
,'Musician 15'
,'Musician 16'
,'Musician 17'
,'Musician 18'
,'Musician 19'
,'Musician 20'
];


// END OF MUSICIAN NAME SETS


var namePrefixes = ['Flaming'
                ,'Black'
                ,'Talking'
                ,'Broken'
                ,'Ashen'
                ,'Rainbow'
                ,'Wandering'
                ,'Lost'
                ,'Breathing'
                ,'Rough'
                ,'Rolling'
                ,'Thundering'
                ,'Hipster'
                ,'Punk'
                ,'Goth'
                ,'White'
                ,'Pale'
                ,'Lunar'
                ,'Mystic'
                ,'Screaming'
                ,'Sexy'
                ,'Diabolical'
                ,'Evil'
                ,'Thumping'
                ,'Ascending'
                ,'Falling'
                ,'Spinning'
                ,'Drooling'
                ,'Secret'
                ,'Mad'
                ,'Hot'
                ,'Veiled'
                ,'Hidden'
                ,'Psychic'
                ,'Nightly'
                ,'Eerie'
                ,'Transparent'
                ,'Wild'
                ,'Smashing'
                ,'Chunking'
                ,'Guns and'
                ,'Roaming'
                ,'Stylish'
                ,'Creepy'
                ,'Nerdy'
                ,'Anti'
                ,'Panoramic'
                ,'McShizzle'
                ,'Pensive'
                ,'Crushing'
                ,'Dead Man'
                ,'Lords of'
                ,'Burnt'
                ,'Wheeled'
                ,'Living'
                ,'Azure'
                ,'Undead'
                ,'Exploding'
                ,'Spiralling'
                ,'Boom-boom'
                ,'Serious'
                ,'Stoic'
                ,'Deep'
                ,'Somber'
                ,'Squirming'
                ,'Vanilla'
                ,'Screeching'
                ,'Thrashing'
                ,'Selective'
                ,'Swift'
                ,'Soaring'
                ,'Mighty'
];

var nameSuffixes = ['Flames'
                ,'Banisters'
                ,'Skulls'
                ,'Unicorns'
                ,'Souls'
                ,'Corpses'
                ,'Flannel'
                ,'Zombies'
                ,'Lampshades'
                ,'Scientists'
                ,'Ghosts'
                ,'Dude and His Merry Gang of Band Nerds'
                ,'Hunters'
                ,'Sirens'
                ,'Lozenges'
                ,'Stones'
                ,'Heads'
                ,'Hands'
                ,'Cerulean'
                ,'Lightning'
                ,'Blades'
                ,'Gang'
                ,'Homeboys'
                ,'Critics'
                ,'Emos'
                ,'Rebels'
                ,'Pirates'
                ,'Pumpkins'
                ,'Roses'
                ,'Demons'
                ,'Tractors'
                ,'Men'
                ,'Gals'
                ,'Riders'
                ,'Ray-Bans'
                ,'Trenchcoats'
                ,'Creepers'
                ,'Gravity'
                ,'Diamonds'
                ,'Mirrors'
                ,'Jefes'
                ,'Esperantos'
                ,'Crimson'
                ,'Wrappers'
                ,'Gauchos'
                ,'Heat'
                ,'Fever'
                ,'Wave'
                ,'Spell'
                ,'Spectacle'
                ,'Voices'
                ,'Group'
                ,'Fliers'
                ,'Homies'
                ,'Rum'
                ,'Wheels'
                ,'Brits'
                ,'Machines'
                ,'Assassination'
                ,'Flint'
                ,'Noises'
                ,'Perspiration'
                ,'Perpetrator'
                ,'Betrayed'
                ,'Wasslers'
                ,'Whirlpool'
                ,'Pistols'
                ,'Boulders'
                ,'Trinkets'
                ,'Rag Dolls'
                ,'Bazookas'
                ,'Popsicle'
                ,'Ice Cubes'
                ,'Banshees'
                ,'Frost'
                ,'Darkness'
                ,'Beat'
                ,'Freeze'
                ,'Kittens'
                ,'Superheroes'
                ,'Bagel'
                ,'Flaxseeds'
                ,'Children'
                ,'Love'
                ,'Equinox'
                ,'Life'
];
